steps:
  - name: ":rspec:"
    command: |
      pwd
      ls -la
      ls -la .buildkite/**
      which bash
      .buildkite/steps/rspec.sh

    plugins:
      docker-compose#v4.11.0:
        run: app
