name: Buildkite Agent
on:
  - push
jobs:
  buildkite-agent:
    strategy:
      matrix:
        node: [1, 2]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      BUILDKITE_AGENT_TOKEN: ${{ secrets.BUILDKITE_AGENT_TOKEN }}
      BUILDKITE_SSH_KEY: ${{ secrets.BUILDKITE_SSH_KEY }}
    steps:
      - name: fix temp dir
        run: |
          ls -la /tmp

      - name: Install docker
        run: |
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh
      - name: Install Buildkite agent
        run: |
          curl -fsSL https://keys.openpgp.org/vks/v1/by-fingerprint/32A37959C2FA5C3C99EFBC32A79206696452D198 | sudo gpg --dearmor -o /usr/share/keyrings/buildkite-agent-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/buildkite-agent-archive-keyring.gpg] https://apt.buildkite.com/buildkite-agent stable main" | sudo tee /etc/apt/sources.list.d/buildkite-agent.list
          sudo apt-get update
          sudo apt-get install -y buildkite-agent
          sudo sed -i "s/xxx/$BUILDKITE_AGENT_TOKEN/g" /etc/buildkite-agent/buildkite-agent.cfg
      - name: give Buildkite permissions to use docker
        run: sudo usermod -aG docker buildkite-agent
      - name: Start Buildkite agent
        run: |
          sudo systemctl enable buildkite-agent
          sudo systemctl start buildkite-agent
      - name: Configure Buildkite SSH
        run: |
          sudo mkdir /var/lib/buildkite-agent/.ssh
          sudo --preserve-env bash -c 'echo "$BUILDKITE_SSH_KEY" > /var/lib/buildkite-agent/.ssh/id_ed25519'
          sudo chown buildkite-agent:buildkite-agent /var/lib/buildkite-agent/.ssh
          sudo chmod 700 /var/lib/buildkite-agent/.ssh
          sudo chown buildkite-agent:buildkite-agent /var/lib/buildkite-agent/.ssh/id_ed25519
          sudo chmod 400 /var/lib/buildkite-agent/.ssh/id_ed25519
      - name: Configure Buildkite agent environment
        run: |
          sudo tee /etc/buildkite-agent/hooks/environment > /dev/null <<'EOF'
          #!/usr/bin/env bash
          export RWX_ACCESS_TOKEN="${{ secrets.RWX_ACCESS_TOKEN }}"
          export PATH="${{ steps.install-ruby.outputs.ruby-prefix }}/bin:$PATH"
          EOF
          sudo chmod +x /etc/buildkite-agent/hooks/environment

      - name: Sleep
        run: sleep 60
